### PR TITLE
added hotkeys to increase or decrease playback speed

### LINKED ISSUE #18: Finer control over demo playback speed
With 2d demos it's usually nice to go a bit faster than 1x speed, however currently the only option bumps playback up to 5x which is a little fast. 5x is useful, but it would be nice to have the ability to watch at 1.5x or 2x speed.

Maybe tapping w could instead increase playback speed by 0.5x at a time? Or double the previous speed (2x, 4x, 8x, etc)?

### PR DESCRIPTION
**Pull request by Linus4**
fixes #18 

shift + w or s to increase or decrease playback speed by 0.25 (min: 0.25, max: 2)

* Does it *need* a hotkey to return to x 1 playback speed? If so, which one?
* Are the speed modifiers okay? (0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2) Or should I leave some out? Feels like 0.75 and 1.75 are useless, but would it make the program that much better to use if I removed those modifiers?
* Does it need modifiers > 2?
* In order to display playback speed modifier:
  - Timer + " x " + Modifier (e.g. `1:25 x 2`)
  - or Timer \n "Playback-Speed: x " + Modifier (current)

### CODE REVIEW

**Comment by langhillie** [comment]
I can see a "reset" hotkey being useful. Perhaps R?
I agree, 0.75 and 1.75 feel pretty useless.
I don't think it needs modifiers above 2x. I think the skipping around with A/D fills that use case.
I think `Timer \n "Playback-Speed: x " + Modifier (current)` is a bit more clear

**Comment by Linus4** [comment]
Thanks for your feedback! I thought about swapping shift+W/S and w/s, too. I'll try it out for a little while - I'm used to fast-forwarding demos in-game with a hotkey (as fast as it goes). Do you switch playback speed often when you're using other demo viewers? I'm currently leaning more towards having w as a super-fast-forward key..
R is a premium hotkey, of course, but as no other function is using it at the moment... :D

**Comment by langhillie** [comment]
Yeah, I change speed pretty often. When reviewing with a team we'll generally play through the round at 1.5 or 2x speed until we see something we should discuss, then we slow down.

**Comment by Linus4** [comment]
Alright, I have incorporated your suggestions. :)

**Pull request merged**
