### PR TITLE
Added Headshot on Killfeed

### PR DESCRIPTION
**Pull request by Asviix**
Still didn't managed to build it, so couldn't test it, will update it if I can build it and test it.

### CODE REVIEW

**Comment by Linus4** [comment]
Hey Asviix, thank you so much for your contribution. Unfortunately, I am preoccupied with work this week and probably next week as well. I will check out your PR as soon as possible and provide some feedback ;)

**Comment by Asviix** [comment]
Cool, I'm having so problems with Go rn so I can't build it, I'll have to wait for your approval on this one xD

**Comment by Linus4** [comment]
The code compiles but at the first kill in my test demo the program crashes: 
`2020/07/11 01:04:19 Text has zero width`
To save on RAM the headshot variable in common.Kill should be a Boolean and then draw.go should decide how to display this information.
Another problem I see is that with your implementation 5 additional characters will be printed in the killfeed which will lead to overlap on the map. There should be a better way that avoids this problem. Maybe there is a character in the font (DejaVuSans.ttf) which could be used?

**Comment by Linus4** [comment]
Another problem I see is that with your implementation 5 additional characters will be printed in the killfeed which will lead to overlap ~~on the map~~ on the egde of the window.

**Comment by Asviix** [comment]
I'll try and fix it when I can

**Comment by Linus4** [comment]
Implemented by #33

**Pull request closed without merging**
